### ISSUE TITLE
Sentinel not working 

### ISSUE THREAD

**Issue by danigosa** [NoneGG/aredis#45] opened 2017-08-19 01:43 UTC
Sentinel does not work, whilst using `redis-cli` or blocking `redis-py` do. Maybe I'm doing something wrong, I noticed that the `Sentinel` object differs from `redis-py` one as it does not allow the keyword argument `socket_timeout` (even being documented as a valid parameter).

* redis-py (1.0.9)
* aredis (2.10.6)
* redis (3.10)

# aredis

```python
import asyncio
from aredis import StrictRedis
REDIS_SERVICE_NAME = 'rsmaster'
REDIS_SENTINELS = [
   ('commons-sentinel1', 26379),
   ('commons-sentinel2', 26379),
   ('commons-sentinel3', 26379)
]
# First just do master connection
s = StrictRedis('commons-redis-master', 6379)
l = asyncio.get_event_loop()
l.run_until_complete(s.keys('*'))
>>> [b'test2', b'test1', b'test3', b'test']
# Now do it through Sentinel object
from aredis.sentinel import Sentinel
s = Sentinel(REDIS_SENTINELS)
l.run_until_complete(s.discover_master('rsmaster'))
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-12-93da80304d53> in <module>()
----> 1 l.run_until_complete(s.discover_master('rsmaster')
      2 )

/usr/lib/python3.5/asyncio/base_events.py in run_until_complete(self, future)
    385             raise RuntimeError('Event loop stopped before Future completed.')
    386
--> 387         return future.result()
    388
    389     def stop(self):

/usr/lib/python3.5/asyncio/futures.py in result(self)
    272             self._tb_logger = None
    273         if self._exception is not None:
--> 274             raise self._exception
    275         return self._result
    276

/usr/lib/python3.5/asyncio/tasks.py in _step(***failed resolving arguments***)
    237                 # We use the `send` method directly, because coroutines
    238                 # don't have `__iter__` and `__next__` methods.
--> 239                 result = coro.send(None)
    240             else:
    241                 result = coro.throw(exc)

/usr/lib/python3.5/site-packages/aredis/sentinel.py in discover_master(self, service_name)
    215         for sentinel_no, sentinel in enumerate(self.sentinels):
    216             try:
--> 217                 masters = await sentinel.sentinel_masters()
    218             except (ConnectionError, TimeoutError):
    219                 continue

/usr/lib/python3.5/site-packages/aredis/commands/sentinel.py in sentinel_masters(self)
    107     async def sentinel_masters(self):
    108         "Returns a list of dictionaries containing each master's state."
--> 109         return await self.execute_command('SENTINEL MASTERS')
    110
    111     async def sentinel_monitor(self, name, ip, port, quorum):

/usr/lib/python3.5/site-packages/aredis/client.py in execute_command(self, *args, **options)
    162         try:
    163             await connection.send_command(*args)
--> 164             return await self.parse_response(connection, command_name, **options)
    165         except (ConnectionError, TimeoutError) as e:
    166             connection.disconnect()

/usr/lib/python3.5/site-packages/aredis/client.py in parse_response(self, connection, command_name, **options)
    177         if command_name in self.response_callbacks:
    178             callback = self.response_callbacks[command_name]
--> 179             return callback(response, **options)
    180         return response
    181

/usr/lib/python3.5/site-packages/aredis/commands/sentinel.py in parse_sentinel_masters(response)
     66     result = {}
     67     for item in response:
---> 68         state = parse_sentinel_state(map(str, item))
     69         result[state['name']] = state
     70     return result

/usr/lib/python3.5/site-packages/aredis/commands/sentinel.py in parse_sentinel_state(item)
     49 def parse_sentinel_state(item):
     50     result = pairs_to_dict_typed(item, SENTINEL_STATE_TYPES)
---> 51     flags = set(result['flags'].split(','))
     52     for name, flag in (('is_master', 'master'), ('is_slave', 'slave'),
     53                        ('is_sdown', 's_down'), ('is_odown', 'o_down'),

KeyError: 'flags'
```

# redis-py
```python
from redis.sentinel import Sentinel
REDIS_SERVICE_NAME = 'rsmaster'
REDIS_SENTINELS = [
   ('commons-sentinel1', 26379),
   ('commons-sentinel2', 26379),
   ('commons-sentinel3', 26379)
]
s = Sentinel(REDIS_SENTINELS, socket_timeout=0.1)
s.discover_master(REDIS_SERVICE_NAME)
>>> ('172.18.0.2', 6379)
m = s.master_for(REDIS_SERVICE_NAME)
m.keys('*')
>>>  [b'test2', b'test1', b'test3', b'test']
```

# redis-cli
```bash
bash-4.3# redis-cli -h commons-sentinel1 -p 26379
commons-sentinel1:26379> SENTINEL get-master-addr-by-name rsmaster
1) "172.18.0.2"
2) "6379"
commons-sentinel1:26379> SENTINEL slaves rsmaster
1)  1) "name"
    2) "172.18.0.4:6379"
    3) "ip"
    4) "172.18.0.4"
    5) "port"
    6) "6379"
    7) "runid"
    8) "3b57a02fdf6be66085b82226a041a7040cc46ca8"
    9) "flags"
   10) "slave"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "699"
   19) "last-ping-reply"
   20) "699"
   21) "down-after-milliseconds"
   22) "5000"
   23) "info-refresh"
   24) "6663"
   25) "role-reported"
   26) "slave"
   27) "role-reported-time"
   28) "1211479"
   29) "master-link-down-time"
   30) "0"
   31) "master-link-status"
   32) "ok"
   33) "master-host"
   34) "172.18.0.2"
   35) "master-port"
   36) "6379"
   37) "slave-priority"
   38) "100"
   39) "slave-repl-offset"
   40) "237851"
2)  1) "name"
    2) "172.18.0.5:6379"
    3) "ip"
    4) "172.18.0.5"
    5) "port"
    6) "6379"
    7) "runid"
    8) "462a4a072ba7e4ded60f65a9b2b520d03c3e5d45"
    9) "flags"
   10) "slave"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "699"
   19) "last-ping-reply"
   20) "698"
   21) "down-after-milliseconds"
   22) "5000"
   23) "info-refresh"
   24) "6663"
   25) "role-reported"
   26) "slave"
   27) "role-reported-time"
   28) "1211469"
   29) "master-link-down-time"
   30) "0"
   31) "master-link-status"
   32) "ok"
   33) "master-host"
   34) "172.18.0.2"
   35) "master-port"
   36) "6379"
   37) "slave-priority"
   38) "100"
   39) "slave-repl-offset"
   40) "237851"
commons-sentinel1:26379> SENTINEL sentinels rsmaster
1)  1) "name"
    2) "bcf7e6582e10f9cc70360348c1a529a6a6ad3a10"
    3) "ip"
    4) "172.18.0.8"
    5) "port"
    6) "26379"
    7) "runid"
    8) "bcf7e6582e10f9cc70360348c1a529a6a6ad3a10"
    9) "flags"
   10) "sentinel"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "133"
   19) "last-ping-reply"
   20) "133"
   21) "down-after-milliseconds"
   22) "5000"
   23) "last-hello-message"
   24) "1378"
   25) "voted-leader"
   26) "?"
   27) "voted-leader-epoch"
   28) "0"
2)  1) "name"
    2) "985e7c3435b9c1593fdb241d668b123f55481ac8"
    3) "ip"
    4) "172.18.0.7"
    5) "port"
    6) "26379"
    7) "runid"
    8) "985e7c3435b9c1593fdb241d668b123f55481ac8"
    9) "flags"
   10) "sentinel"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "133"
   19) "last-ping-reply"
   20) "133"
   21) "down-after-milliseconds"
   22) "5000"
   23) "last-hello-message"
   24) "800"
   25) "voted-leader"
   26) "?"
   27) "voted-leader-epoch"
   28) "0"
commons-sentinel1:26379> SENTINEL sentinels rsmaster
1)  1) "name"
    2) "bcf7e6582e10f9cc70360348c1a529a6a6ad3a10"
    3) "ip"
    4) "172.18.0.8"
    5) "port"
    6) "26379"
    7) "runid"
    8) "bcf7e6582e10f9cc70360348c1a529a6a6ad3a10"
    9) "flags"
   10) "sentinel"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "972"
   19) "last-ping-reply"
   20) "972"
   21) "down-after-milliseconds"
   22) "5000"
   23) "last-hello-message"
   24) "1371"
   25) "voted-leader"
   26) "?"
   27) "voted-leader-epoch"
   28) "0"
2)  1) "name"
    2) "985e7c3435b9c1593fdb241d668b123f55481ac8"
    3) "ip"
    4) "172.18.0.7"
    5) "port"
    6) "26379"
    7) "runid"
    8) "985e7c3435b9c1593fdb241d668b123f55481ac8"
    9) "flags"
   10) "sentinel"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "972"
   19) "last-ping-reply"
   20) "972"
   21) "down-after-milliseconds"
   22) "5000"
   23) "last-hello-message"
   24) "573"
   25) "voted-leader"
   26) "?"
   27) "voted-leader-epoch"
   28) "0"
```

**Comment by NoneGG** [comment] 2017-08-19 06:56
@danigosa 
Thank you for your bug report firstly. 

The main problem is caused by the function `parse_sentinel_masters`, it try to find key `flag` but there is only `b'flag'` in response if `decode_response` is set to `False`. 

The bug is now fixed(your example code can be run smoothly in my env now) and related document will all get fixed as soon as possible.
If you don't mind, could you try fixed version by command below?
`pip install git+https://github.com/NoneGG/aredis.git` 

If there are still other problems please let me know at the first time.

**Comment by danigosa** [comment] 2017-08-19 14:09
Hi @NoneGG , now it works smoothly, when do you plan to release this in pypi? We cannot use _pointed to master_ pip packages in production (for obvious reasons). Thanks for the quick response!

**Comment by NoneGG** [comment] 2017-08-19 15:18
I am doing development about cluster transaction and it is almost finished. So the next release will be published in at most one week. I will try to finish the development as soon as possible.

**Comment by danigosa** [comment] 2017-08-19 23:07
@NoneGG sounds good, thanks for the nice work and for sharing it 👍

**Comment by NoneGG** [comment] 2017-08-20 01:44
If there are other problems about aredis, please let me know. I will fix it as soon as possible~

**Closed by NoneGG** 2017-08-20 01:44 UTC

**Comment by NoneGG** [comment] 2017-08-24 04:24
@danigosa 
FYI, release v1.1.0 is published last night~
