### ISSUE TITLE
a broken connection will always be returned to pool

### ISSUE THREAD

**Issue by myrfy001** [NoneGG/aredis#48] opened 2017-08-22 09:44 UTC
If the server side set a timeout value, and the server close a connection because of idle, then ,this broken connection will stay in the pool forever.

and because pop and append is used to implement the pool, the released broken connection will be poped for next request and so on.

**Comment by NoneGG** [comment] 2017-08-22 15:04
@myrfy001 
Than you for the bug report again~ And sorry for my late response.

Could you give me a case to reproduce the problem? I am not sure where the problem is.

The broken connection with a timeout value is the connection disconnected due to timeout, but it will reconnect again if being used again, so it is thought safe to release connection with timeout set to the pool.

**Comment by myrfy001** [comment] 2017-08-23 02:56
Sorry, I didn't noticed that the connection will try to reconnect, I only read the code in client.py and pool.py...but i think the reconnect step still has some problem.

if #47 is not fixed, and a request is going to be sent on a beoken connection, then a connection error will be raised, then `try_random_node` flag is set to true, on the next loop, because `try_random_node` is set, a random node will be choosed, and #47 will happen. And the broken connection is put back to the pool in  the *final* block of the *try* statement. The next request will still get the broken connection and so on.

So, the problem is, it seems that the reconnect maybe fail, and lead to `try_random_node` flag be set.

I used the redis cluster docker image by Grokzen to setup a test environment, use `config set timeout 1` on all of the nodes, and use asyncio to make about 10 coroutines to send get command.

**Comment by myrfy001** [comment] 2017-08-23 03:17
I think if a connection was built, and then disconnected by the server, `Connection._reader` and `Connection._writer` won't be set to `None`, so, in fact, there is no reconnect at all.

**Comment by NoneGG** [comment] 2017-08-23 07:13
@myrfy001 
Actually disconnection is launched by client and both `Connection._reader` and `Connection._writer` are set to `None` during disconnection. 
About the test case, i will try to reproduce the problem later tonight to find out the problem~

**Comment by myrfy001** [comment] 2017-08-23 07:42
connection will be disconnected in `_execute_command_on_nodes ()`, that's fine, but in the following code, if a broken connection is used, it will not be closed.
https://github.com/NoneGG/aredis/blob/d84a5ad6a4d4510f0801ef46323b1f1a902e0a19/aredis/client.py#L406

The `try` statement and close a connection if broken should be checked at every place where network io may happens,

**Comment by NoneGG** [comment] 2017-08-23 08:32
Your opinion is reasonable, and actually `Connection.disconnect` is called in `Connection.read_response` and `Connection.send_packed_command` when timeout error or other unknown errors take place. And reconnection is tried if connection found not connected in `Connection.send_packed_command`. 

The reconnecting and disconnecting issues are mainly thought to be the underlying structure of client.

**Comment by myrfy001** [comment] 2017-08-23 08:51
sorry for the previous comment, i didn't dig deeply into the code.

It was because of #47, the broken connection can't be reconnected.

I think this issue can be closed.

**Comment by NoneGG** [comment] 2017-08-23 10:19
Thank you for the bug report and discussion on connection, it is really helpful for those who has doubt about similar problems~
If you have other problems please tell me, i will fix them as soon as i can.

The bug refered in issue #47 is already fixed and will be released in next release soon (in this week).

**Closed by NoneGG** 2017-08-23 10:19 UTC
