### ISSUE TITLE
UnicodeDecodeError when receiving pickled response from pubsub

### ISSUE THREAD

**Issue by hballard** [NoneGG/aredis#39] opened 2017-07-24 16:40 UTC
Hello.  Thanks for the excellent library.  The current Pubsub implementation decodes the whole response object from bytes, if it is a bytes object.  This is different from redis-py, which just converts the response type only and then passes the rest of the response through to the client.  This poses a problem with objects that are pickle (or any serialization) before they are published to the redis pubsub.

relevant code from areds:
`def handle_message(self, response, ignore_subscribe_messages=False):
        """
        Parses a pub/sub message. If the channel or pattern was subscribed to
        with a message handler, the handler is invoked instead of a parsed
        message being returned.
        """
        response = [x.decode() if isinstance(x, bytes) else x for x in response]`

relevant code from redis-py:
`def handle_message(self, response, ignore_subscribe_messages=False):
        """
        Parses a pub/sub message. If the channel or pattern was subscribed to
        with a message handler, the handler is invoked instead of a parsed
        message being returned.
        """
        message_type = nativestr(response[0])`

the natrivestr implementation is:

`def nativestr(x):
        return x if isinstance(x, str) else x.decode('utf-8', 'replace')`

Is this different than the redis-py implementation for a specific reason?  It causes  a UnitcodeDecodeErrror when an aredis pubsub client instance tries to decode a pickled object I've published.  Is their another way you'd recommend I handle this?  Thanks!

**Comment by NoneGG** [comment] 2017-07-25 02:36
@hballard 
Thank you for your bug report. 

This is a historical bug introduced by aredis encoding issues, which is caused by my design mistake. 

In former release of aredis(1.0.8-), decode reponse is not supported and user are considered to handle decoding themselves. It is proved to be foolish, so i tried to support decode reponse in version 1.0.9. 
This situation is not considered suitably.

I will fix this and add related test cases in at most two days.

**Comment by hballard** [comment] 2017-07-25 03:25
Wow!  That is fast.  You did an excellent job on this library...design mistake or not (a minor one in my opinion if you want to call it that).  I'm building a graphql subscriptions client and need a drop-in replacement to support asyncio as a concurrency executor for my pubsub.  This is way easier to port from redis-py, than the other asyncio redis clients out there currently, IMHO.  Thanks!

**Comment by NoneGG** [comment] 2017-07-25 10:11
@hballard 
Thank you for your high evaluation on aredis ^-^
This bug is fixed and pushed to master, if you don't mind, could you reinstall aredis by command below and try your code again?
`UnicodeDecodeError when receiving pickled response from pubsub`
Please let me know If there are still other problems

**Comment by hballard** [comment] 2017-07-25 20:28
I'll try this out this evening and let you know what I think for sure.  Thanks for the quick turnaround!

**Comment by NoneGG** [comment] 2017-07-26 02:05
You are welcome~
Looking forward to your opinion!

**Comment by hballard** [comment] 2017-07-26 02:27
All my tests pass like they did before w/ redis-py.  If you are interested, I've ported a graphql subscription client (uses websockets) for python [here](https://github.com/hballard/graphql-python-subscriptions).  It currently only works w/ Gevent...but I'm working on Asyncio compatability.  My plan is to use aredis for my redis pubsub client for the Asyncio executor (I'm using redis-py for non Asyncio executors).  I'm probably a few more days from publishing the Asyncio working code to master.  Thanks!

**Comment by NoneGG** [comment] 2017-07-26 03:39
It seems to be interesting, i will try and maybe i can make some contribution to your project~
Actually i mainly work on storage related stuff in my daily job and not so familiar with graphql, it may take some time for me to get familiar with that.

If you don't mind, i will close this issue~

**Comment by hballard** [comment] 2017-07-26 03:40
Sounds good.  Thanks.

**Closed** 2017-07-26 03:42 UTC
