### ISSUE TITLE
Python 3.8 raises AttributeError on timeout

### ISSUE THREAD

**Issue by olii** [NoneGG/aredis#141] opened 2020-02-27 13:58 UTC
## Checklist

- Python version 3.8
- hiredis
- just asyncio event loop
- Does issue exists against the `master` branch of aredis? YES

## Steps to reproduce
Run sentinel and at least 2 slaves. During runtime kill the master and let the sentinel vote for new slave. Run some redis calls e.g. `set` or `ping`.

## Expected behavior
During the time the master is down and new master is not voted all the calls to the redis should end with an exception type `aredis.exceptions.ConnectionError`.

## Actual behavior
`AttributeError` is raised.

https://github.com/NoneGG/aredis/blob/master/aredis/connection.py#L467

```
  File "/.../lib/python3.8/site-packages/aredis/pipeline.py", line 300, in execute
    return await exec(conn, stack, raise_on_error)
  File "/.../lib/python3.8/site-packages/aredis/pipeline.py", line 143, in _execute_transaction
    await connection.send_packed_command(all_cmds)
  File "/.../lib/python3.8/site-packages/aredis/connection.py", line 464, in send_packed_command
    except asyncio.futures.TimeoutError:
AttributeError: module 'asyncio.futures' has no attribute 'TimeoutError'
exception module 'asyncio.futures' has no attribute 'TimeoutError'
```

## How to fix this

Use `asyncio.TimeoutError` instead of `asyncio.futures.TimeoutError`

**Comment by NoneGG** [comment] 2020-02-29 14:47
@olii Thank you for bug report, actually there was similar bug(`asyncio.CancelledError`) will be fixed soon

**Comment by NoneGG** [comment] 2020-03-01 16:14
Feel free to reopen this issue if the problem is not solved~

**Closed by NoneGG** 2020-03-01 16:14 UTC
